### ISSUE TITLE
the code formatting changes

### ISSUE THREAD

**Issue by asgeirtj** [jiang-taibai/chatgpt-with-date#3]
hello

im intereseted in extension but not in it changing md formatting colors

![Button CSS Invert Lightness Google Chrome 002008](https://github.com/jiang-taibai/chatgpt-with-date/assets/27446620/d75a2c5e-1c4c-4785-b76b-cbdc1483e510)

<img width="1106" alt="image" src="https://github.com/jiang-taibai/chatgpt-with-date/assets/27446620/05839464-1f71-4310-bfd6-c7a0ef849fbb">

what is the reason for this?

**Comment by jiang-taibai** [comment]
I'm sorry, I'm a little confused as to what you mean. The original code in this extension does not involve this code, may I ask where this code comes from? Is it the timestamp CSS code that ChatGPT generates using the prompts from this extension?

**Comment by asgeirtj** [comment]
it's just to showcase that markdown code block inside chatgpt get's it's
css styles changed with your extension for some reason which I don't
understand can't you see it :)

Kveðja / Regards, Ásgeir

**Comment by jiang-taibai** [comment]
Can you please attach the HTML, CSS and JavaScript code you wrote in the configuration panel for me? I can help you to modify the code to achieve the effect you want.
You can also click on the leftmost of the five buttons in the top right corner of the configuration panel to reset all configurations. The situation you describe should not occur in the default configuration.

**Comment by asgeirtj** [comment]
[image: chatgpt.comc76b1430c-2869-4c18-bb96-b8a3ab28edde Google Chrome
002365.png]its just default right

Kveðja / Regards, Ásgeir

**Comment by jiang-taibai** [comment]
I checked the code carefully and realized that I had introduced the `highlight.js` library file with the intention of highlighting the code in the configuration panel, but it was affecting the code style of the original page.

Thanks for your feedback, I'll fix the bug in time!

**Comment by asgeirtj** [comment]
No problem, thanks!

Kveðja / Regards, Ásgeir

**Comment by asgeirtj** [comment]
Awesome, thanks for the update!

Kveðja / Regards, Ásgeir
