### ISSUE TITLE
允许跨源资源共享（CORS）请求 在哪里可以设置？

### ISSUE THREAD

**Issue by fugangcui** [jiang-taibai/chatgpt-with-date#5]
<img width="887" alt="image" src="https://github.com/user-attachments/assets/bfc4951a-cd4d-4a4f-ad36-2bce4a342380">

**Comment by jiang-taibai** [comment]
您好，文档没有描述清楚，是在首次访问配置面板时，会自动弹出此CORS请求允许，暂时不允许也不影响插件正常使用，只会影响配置面板。稍后我完善一下文档，谢谢您的反馈。
