### ISSUE TITLE
根本就没有弹出配置面板

### ISSUE THREAD

**Issue by wldcd** [jiang-taibai/chatgpt-with-date#6]
safari也没有 chrome也没有

全部该下的都下了 extension，script，everything
![Screenshot 2024-09-01 at 20 52 54](https://github.com/user-attachments/assets/103f0f2e-ab44-4771-98ca-b2eb51a2c764)

**Comment by wldcd** [comment]
![Screenshot 2024-09-01 at 20 53 18](https://github.com/user-attachments/assets/071d5807-5251-40ca-b73f-943024634f99)

**Comment by wldcd** [comment]
![Screenshot 2024-09-01 at 20 53 34](https://github.com/user-attachments/assets/0a59ab45-ffd4-4e92-baa1-2e72edb17792)

**Comment by jiang-taibai** [comment]
看到您发的第三张图片，显示“Please enable developer mode to allow userscript injection.”，可以参考 [Q209: 开发者模式用于运行用户脚本](https://www.tampermonkey.net/faq.php#Q209) 试着开启开发者模式哦~
